#!/usr/bin/env bash
set -euo pipefail

SRC_DIR="$(cd "$(dirname "$0")/../src" && pwd)"
YML="${SRC_DIR}/project.yml"
METADATA="${SRC_DIR}/metadata.tex"

if [[ ! -f "$YML" ]]; then
  echo "Error: project.yml not found at ${YML}"
  exit 1
fi

yaml_get() {
  local key="$1"
  grep "^${key}:" "$YML" | head -1 | sed "s/^${key}:[[:space:]]*//" | sed 's/^"//;s/"$//'
}

yaml_list() {
  local key="$1"
  local in_block=0
  while IFS= read -r line; do
    if [[ "$line" =~ ^${key}: ]]; then
      in_block=1
      continue
    fi
    if [[ $in_block -eq 1 ]]; then
      if [[ "$line" =~ ^[[:space:]]+- ]]; then
        echo "$line" | sed 's/^[[:space:]]*-[[:space:]]*//' | sed 's/^"//;s/"$//'
      else
        break
      fi
    fi
  done < "$YML"
}

BOOK_TITLE=$(yaml_get "book_title")
BOOK_SUBTITLE=$(yaml_get "book_subtitle")
UNIVERSITY=$(yaml_get "university_name")
DEPARTMENT=$(yaml_get "department_name")
PROJECT=$(yaml_get "project_name")
ACADEMIC_YEAR=$(yaml_get "academic_year")
RELEASE_DATE=$(yaml_get "release_date")
UNI_LOGO=$(yaml_get "university_logo")
PROJECT_LOGO=$(yaml_get "project_logo")

mapfile -t MEMBERS < <(yaml_list "team_members")
mapfile -t SUPERVISORS < <(yaml_list "supervisors")

PROJECT_ESC="${PROJECT//&/\\&}"

MEMBERS_LINES=""
for i in "${!MEMBERS[@]}"; do
  if [[ $i -gt 0 ]]; then
    MEMBERS_LINES+=' \\'
    MEMBERS_LINES+=$'\n'
  fi
  MEMBERS_LINES+="  ${MEMBERS[$i]}"
done

SUPERVISORS_LINES=""
for i in "${!SUPERVISORS[@]}"; do
  if [[ $i -gt 0 ]]; then
    SUPERVISORS_LINES+=' \and'
    SUPERVISORS_LINES+=$'\n'
  fi
  SUPERVISORS_LINES+="  ${SUPERVISORS[$i]}"
done

# Write metadata.tex (fully auto-generated — safe to overwrite)
cat > "$METADATA" << EOF
% ─── Metadata (auto-generated by scripts/init.sh from project.yml) ───────────
\\newcommand{\\BookTitle}{${BOOK_TITLE}}
\\newcommand{\\BookSubtitle}{${BOOK_SUBTITLE}}
\\newcommand{\\UniversityName}{${UNIVERSITY}}
\\newcommand{\\DepartmentName}{${DEPARTMENT}}
\\newcommand{\\ProjectName}{${PROJECT_ESC}}
\\newcommand{\\AcademicYear}{${ACADEMIC_YEAR}}

% Team members
\\newcommand{\\TeamMembers}{%
${MEMBERS_LINES}%
}

% Supervisors
\\newcommand{\\Supervisors}{%
${SUPERVISORS_LINES}%
}

% Date
\\newcommand{\\ReleaseDate}{${RELEASE_DATE}}

% Logo filenames
\\newcommand{\\UniversityLogo}{${UNI_LOGO}}
\\newcommand{\\ProjectLogo}{${PROJECT_LOGO}}
EOF

echo "[DONE] metadata.tex generated from project.yml"
echo ""
echo "   Book Title:  ${BOOK_TITLE}"
echo "   Project:     ${PROJECT}"
echo "   University:  ${UNIVERSITY}"
echo "   Members:     ${#MEMBERS[@]}"
echo "   Supervisors: ${#SUPERVISORS[@]}"
echo ""
echo "Run 'make build' to compile."
